# Generated by Django 3.0.6 on 2020-05-16 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('edition', models.CharField(max_length=255, null=True)),
                ('publication_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('authors', models.ManyToManyField(to='core.Author')),
            ],
        ),
    ]
